# Generated by Django 4.1.7 on 2023-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_report_file_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
