# Generated by Django 4.1.7 on 2023-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_certificatemodel_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='user_info',
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='extra_language_skills_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Əlavə dil bilikləri'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='general_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Ümumi suallar'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='language_skills_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Dil bilikləri'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='olympiad_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Olimpiada sualları'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='program_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Proqram bilikləri'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='secondary_education_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Orta, texniki və ali təhsil sualları'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='special_skills_certificate_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Xüsusi bacarıq sertifikatları'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='special_skills_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Xüsusi bacarıqlar'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='sport_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='İdman sualları'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='work_experience_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='İş təcrübəsi'),
        ),
    ]
