# Generated by Django 4.1.7 on 2023-09-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_reportmodel_user_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.reportmodel'),
        ),
    ]
