# Generated by Django 4.1.7 on 2023-09-08 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_useraccount_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_info',
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='user_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
