# Generated by Django 4.1.7 on 2023-09-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_useraccount_user_info_reportmodel_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='user_info',
            new_name='user',
        ),
    ]
