# Generated by Django 4.1.7 on 2023-09-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_user_info_reportmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='extra_language_skills_questions',
        ),
    ]
