# Generated by Django 4.1.7 on 2023-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_reportmodel_extra_language_skills_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='education_score',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='language_score',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='program_score',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='special_skills_score',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='sport_score',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='work_experiance_score',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
        ),
    ]
