# Generated by Django 4.1.7 on 2023-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_reportmodel_education_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='extra_language_skills_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Əlavə dil bilikləri'),
        ),
    ]
