# Generated by Django 4.1.7 on 2023-09-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_reportmodel_extra_language_skills_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='user',
        ),
    ]
