# Generated by Django 4.1.7 on 2023-09-12 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_useraccountfilepage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='report_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='users.useraccountfilepage'),
        ),
        migrations.AlterField(
            model_name='useraccountfilepage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
