# Generated by Django 4.1.7 on 2023-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_reportmodel_report_file_alter_reportmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='sport2_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='İdman sualları2'),
        ),
    ]
