# Generated by Django 4.1.7 on 2023-10-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_reportmodel_sport2_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='test',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='report_test',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
