# Generated by Django 4.1.7 on 2023-09-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_reportmodel_sport2_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='report_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.useraccountfilepage'),
        ),
    ]
