# Generated by Django 4.1.7 on 2023-09-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_reportmodel_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='report_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.useraccountfilepage'),
        ),
    ]
