# Generated by Django 4.1.7 on 2023-10-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_rename_county_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='file_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
