# Generated by Django 4.1.7 on 2023-10-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_useraccount_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('sample_summary', models.TextField()),
                ('sample_job_title', models.CharField(max_length=255)),
                ('profile_photo', models.URLField()),
                ('links', models.JSONField()),
                ('secondary_education', models.JSONField()),
                ('programSkills', models.JSONField()),
                ('work_experience', models.JSONField()),
                ('resume_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='users.useraccountfilepage')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.DeleteModel(
            name='UserCV',
        ),
    ]
