# Generated by Django 4.1.7 on 2023-09-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answer_answer_weight_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='sub_answer_question',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='SubAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_answer_title', models.CharField(max_length=150)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subanswers', to='app.answer')),
            ],
        ),
    ]
