# Generated by Django 4.1.7 on 2023-12-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subanswer_sub_answer_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subanswer',
            old_name='sub_answer_weight_for_hashing',
            new_name='answer_weight',
        ),
    ]
