# Generated by Django 4.1.7 on 2023-12-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_sub_answer_weight_for_hashing_subanswer_answer_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subanswer',
            old_name='sub_answer_title',
            new_name='answer_title',
        ),
    ]
